# Generated by Django 5.2 on 2025-05-06 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimadores', '0002_estimador_is_active'),
        ('proyectos_C', '0005_alter_proyecto_cc_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_C_Estimador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimadores.estimador')),
                ('proyecto_c', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_C_estimador_relation', to='proyectos_C.proyecto_cc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
