# Generated by Django 5.0.14 on 2025-06-18 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_c_Estimador', '0001_initial'),
        ('proyectos_C', '0005_alter_proyecto_cc_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_c_estimador',
            name='proyecto_c',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_estimador_relation', to='proyectos_C.proyecto_cc'),
        ),
    ]
