# Generated by Django 5.0.14 on 2025-07-29 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLicitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'verbose_name': 'Categoria de Licitacion',
                'verbose_name_plural': 'Categorias de Licitacion',
            },
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq', models.CharField(max_length=255, unique=True, verbose_name='Numero de Licitacion (RFQ)')),
                ('rfq_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tipo de RFQ')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicacion')),
                ('closed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('closed_hour', models.TimeField(blank=True, null=True, verbose_name='Hora de Cierre')),
                ('estado_lic', models.CharField(blank=True, choices=[('Acto Desierto', 'Acto Desierto'), ('Adjudicacion', 'Adjudicacion'), ('Anuncio Vencido', 'Anuncio Vencido'), ('Cancelacion del Acto', 'Cancelacion del Acto'), ('Enmendada', 'Enmendada'), ('Evaluacion', 'Evaluacion')], max_length=50, null=True, verbose_name='Estado de Licitacion')),
                ('gral_desc', models.TextField(blank=True, null=True, verbose_name='Descripcion General')),
                ('proc_area', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licitaciones.categorylicitacion', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Licitacion',
                'verbose_name_plural': 'Licitaciones',
            },
        ),
        migrations.CreateModel(
            name='Enmienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enmienda_id', models.IntegerField(verbose_name='ID de Enmienda')),
                ('enmienda_desc', models.TextField(blank=True, null=True, verbose_name='Descripcion de Enmienda')),
                ('fecha_enmienda', models.DateField(blank=True, null=True, verbose_name='Fecha de Enmienda')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enmiendas', to='licitaciones.licitacion', verbose_name='Licitacion')),
            ],
            options={
                'verbose_name': 'Enmienda',
                'verbose_name_plural': 'Enmiendas',
                'unique_together': {('licitacion', 'enmienda_id')},
            },
        ),
        migrations.CreateModel(
            name='Propuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_proponente_id', models.CharField(max_length=255, verbose_name='ID Proponente de Oferta')),
                ('bid_line_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de Línea de Oferta')),
                ('bid_line_no', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número de Línea de Oferta')),
                ('bid_status', models.CharField(blank=True, choices=[('CUMPLE', 'CUMPLE'), ('DESCALIFICADA', 'DESCALIFICADA'), ('INCUMPLE', 'INCUMPLE'), ('NO CONSIDERADA', 'NO CONSIDERADA'), ('PROPUESTA REVISADA', 'PROPUESTA REVISADA'), ('', 'Vacío')], max_length=50, null=True, verbose_name='Estado de Oferta')),
                ('bid_vendor_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre de Vendedor de Oferta')),
                ('rfq_closed_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre de RFQ (Propuesta)')),
                ('rfq_method', models.CharField(blank=True, max_length=255, null=True, verbose_name='Método de RFQ (Propuesta)')),
                ('resultado', models.CharField(blank=True, max_length=255, null=True, verbose_name='Resultado (Propuesta)')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propuestas', to='licitaciones.licitacion', verbose_name='Licitación')),
            ],
            options={
                'verbose_name': 'Propuesta',
                'verbose_name_plural': 'Propuestas',
                'unique_together': {('licitacion', 'bid_proponente_id', 'bid_line_no')},
            },
        ),
    ]
