# Generated by Django 5.0.14 on 2025-07-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacion',
            name='estado_lic',
            field=models.CharField(blank=True, choices=[('Acto Desierto', 'Acto Desierto'), ('Adjudicacion', 'Adjudicacion'), ('Anuncio Vencido', 'Anuncio Vencido'), ('Cancelacion Del Acto', 'Cancelacion Del Acto'), ('Enmendada', 'Enmendada'), ('Evaluacion', 'Evaluacion')], max_length=50, null=True, verbose_name='Estado de Licitacion'),
        ),
    ]
