# Generated by Django 5.0.14 on 2025-07-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0002_alter_licitacion_estado_lic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuesta',
            name='bid_proponente_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Proponente de Oferta'),
        ),
    ]
