# Generated by Django 5.2 on 2025-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('title', models.TextField()),
                ('seccion', models.CharField(max_length=20)),
                ('coordinador', models.CharField(max_length=200)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_envio_FIO', models.DateTimeField(blank=True, null=True)),
                ('fecha_sol_fondos_aprob', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibo_fondos_aprob', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('IN', 'INGENIERIA'), ('CO', 'CONTRATOS'), ('AD', 'ADJUDICADO'), ('PEAD', 'PENDIENTE ADJ.'), ('CA', 'CANCELADO'), ('FI', 'FUERZAS INTERNAS'), ('DE', 'DESIERTA'), ('PE', 'PENDIENTE')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
