# Generated by Django 5.0.14 on 2025-08-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SIA', '0001_initial'),
        ('licitaciones', '0001_initial'),
        ('proyectos_E', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('title', models.TextField(blank=True, null=True)),
                ('seccion', models.CharField(blank=True, max_length=20, null=True)),
                ('coordinador', models.CharField(blank=True, max_length=200, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, editable=False, help_text='Año fiscal calculado a partir del código', null=True)),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('fecha_envio_FIO', models.DateField(blank=True, null=True)),
                ('fecha_sol_fondos_aprob', models.DateTimeField(blank=True, null=True)),
                ('fecha_recibo_fondos_aprob', models.DateTimeField(blank=True, null=True)),
                ('asignacion_presup_final', models.FloatField(blank=True, null=True)),
                ('precio_acp', models.FloatField(blank=True, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'Adjudicado'), (2, 'Cancelado'), (3, 'Contratos'), (4, 'Coordinador'), (5, 'Desierta'), (6, 'Diferido'), (7, 'FMCM'), (8, 'Fuerzas Internas'), (9, 'Ingenieria'), (10, 'IPIS'), (11, 'ISC'), (12, 'No Adjudicada'), (13, 'Pendiente')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_CC_Estimado_Conceptual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimado_conceptual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_estimado_conceptual_e', to='proyectos_E.proyecto_e')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_estimado_conceptual_cc', to='proyectos_C.proyecto_cc')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_CC_Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_C.proyecto_cc')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto_CC_SIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_C.proyecto_cc')),
                ('sia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.tblproyectos')),
            ],
        ),
    ]
