# Generated by Django 5.2 on 2025-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_cc',
            name='asignacion_presup_final',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto_cc',
            name='precio_acp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto_cc',
            name='coordinador',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto_cc',
            name='estado',
            field=models.CharField(blank=True, choices=[(1, 'Adjudicado'), (2, 'Cancelado'), (3, 'Contratos'), (4, 'Coordinador'), (5, 'Desierta'), (6, 'Diferido'), (7, 'FMCM'), (8, 'Fuerzas Internas'), (9, 'Ingenieria'), (10, 'IPIS'), (11, 'ISC'), (12, 'No Adjudicada'), (13, 'Pendiente')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto_cc',
            name='fecha_entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='proyecto_cc',
            name='fecha_envio_FIO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto_cc',
            name='seccion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
