# Generated by Django 5.0.14 on 2026-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0002_proyecto_cc_secciones_mf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_cc',
            name='estado',
            field=models.IntegerField(blank=True, choices=[(1, 'Adjudicado'), (2, 'Cancelado'), (3, 'Contratos'), (4, 'Coordinador'), (5, 'Desierta'), (6, 'Diferido'), (7, 'FMCM'), (8, 'Fuerzas Internas'), (9, 'Ingenieria'), (10, 'IPIS'), (11, 'ISC'), (12, 'No Adjudicada'), (13, 'Pendiente'), (14, 'Dueño')], null=True),
        ),
    ]
