# Generated by Django 5.2 on 2025-04-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0002_proyecto_cc_asignacion_presup_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_cc',
            name='fecha_entrada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
