# Generated by Django 5.2 on 2025-04-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0003_alter_proyecto_cc_fecha_entrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_cc',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
