# Generated by Django 5.0.14 on 2025-06-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0005_alter_proyecto_cc_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_cc',
            name='fiscal_year',
            field=models.IntegerField(blank=True, editable=False, help_text='Año fiscal calculado a partir del código', null=True),
        ),
    ]
