# Generated by Django 5.0.14 on 2025-07-29 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licitaciones', '0002_alter_licitacion_estado_lic'),
        ('proyectos_C', '0006_proyecto_cc_fiscal_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_CC_Licitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='licitaciones.licitacion')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_C.proyecto_cc')),
            ],
        ),
    ]
