# Generated by Django 5.0.14 on 2025-07-30 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0007_proyecto_cc_licitacion'),
        ('proyectos_E', '0003_proyecto_e_asignacion_presup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_CC_Estimado_Conceptual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimado_conceptual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_E.proyecto_e')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_C.proyecto_cc')),
            ],
        ),
    ]
