# Generated by Django 5.0.14 on 2025-07-30 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_C', '0008_proyecto_cc_estimado_conceptual'),
        ('proyectos_E', '0003_proyecto_e_asignacion_presup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_cc_estimado_conceptual',
            name='estimado_conceptual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_estimado_conceptual_e', to='proyectos_E.proyecto_e'),
        ),
        migrations.AlterField(
            model_name='proyecto_cc_estimado_conceptual',
            name='proyecto_cc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_estimado_conceptual_cc', to='proyectos_C.proyecto_cc'),
        ),
    ]
