# Generated by Django 5.0.14 on 2025-08-09 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos_C', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_solicitante', models.CharField(max_length=5)),
                ('nip', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_estimada_entrega_owner', models.DateField(blank=True, null=True)),
                ('fiscal_year', models.PositiveIntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField(blank=True, choices=[(1, 'SIN INICIAR'), (2, 'EN PROCESO'), (3, 'ENTREGADO')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_proyectos', to='proyectos_C.proyecto_cc')),
            ],
        ),
    ]
