# Generated by Django 5.0.14 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_E',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=25)),
                ('title', models.TextField()),
                ('fecha_entrada', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('seccion', models.CharField(blank=True, max_length=25, null=True)),
                ('coordinador', models.CharField(blank=True, max_length=100, null=True)),
                ('bldg', models.CharField(blank=True, max_length=20, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fiscal_year', models.IntegerField(blank=True, null=True)),
                ('asignacion_presup', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
