# Generated by Django 5.0.14 on 2025-08-07 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_E', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_diseno_inic_ar', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inic_ic', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inic_ie', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inic_ih', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inie_dm', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inie_ee', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inie_sm', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inig_ig', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inig_pe', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inio_ce', models.FloatField(blank=True, null=True)),
                ('hr_diseno_inio_es', models.FloatField(blank=True, null=True)),
                ('hr_diseno_init', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inic_ar', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inic_ic', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inic_ie', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inic_ih', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inie_dm', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inie_ee', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inie_sm', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inig_ig', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inig_pe', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inio_ce', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_inio_es', models.FloatField(blank=True, null=True)),
                ('hr_apoyo_init', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proyecto_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_E.proyecto_e')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
