# Generated by Django 5.2 on 2025-04-22 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_E', '0002_rename_descripcion_proyecto_e_title_proyecto_e_bldg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto_e',
            name='asignacion_presup',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
