# Generated by Django 5.0.14 on 2025-08-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_E', '0002_horasapoyo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horasapoyo',
            name='revision',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
