# Generated by Django 5.0.14 on 2025-08-07 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_E', '0003_horasapoyo_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horasapoyo',
            name='proyecto_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas_de_apoyo', to='proyectos_E.proyecto_e'),
        ),
    ]
