# Generated by Django 5.0.14 on 2025-08-19 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0002_tblproyectos_horas_especificador_and_more'),
        ('proyectos_E', '0004_alter_horasapoyo_proyecto_e'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_E_SIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proyecto_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_E.proyecto_e')),
                ('sia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.tblproyectos')),
            ],
        ),
    ]
