# Generated by Django 5.0.14 on 2025-08-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especificadores', '0001_initial'),
        ('proyectos_C', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_C_Especificador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('especificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especificadores.especificador')),
                ('proyecto_cc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_CC_especificador_relation', to='proyectos_C.proyecto_cc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
