# Generated by Django 5.0.14 on 2025-08-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especificadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especificador',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
