# Generated by Django 5.2 on 2025-04-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimador',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
