# Generated by Django 5.2 on 2025-04-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estimadores', '0001_initial'),
        ('proyectos_E', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_E_Estimador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estimadores.estimador')),
                ('proyecto_e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos_E.proyecto_e')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
