# Generated by Django 5.2 on 2025-04-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto_E_Estimador', '0001_initial'),
        ('proyectos_E', '0003_proyecto_e_asignacion_presup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto_e_estimador',
            name='proyecto_e',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_E_estimador_relation', to='proyectos_E.proyecto_e'),
        ),
    ]
