# Generated by Django 5.0.14 on 2025-06-19 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto_SE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('title', models.TextField(blank=True, null=True)),
                ('fecha_entrada', models.DateField()),
                ('fecha_salida', models.DateField()),
                ('fecha_sol_fondos', models.DateField()),
                ('fecha_sol_fondos_aprobados', models.DateField()),
                ('comentarios', models.TextField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
