# Generated by Django 5.0.14 on 2025-08-05 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblProyectos',
            fields=[
                ('CodProyecto', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('NomProyecto', models.TextField(blank=True, null=True)),
                ('CodCuenta', models.PositiveIntegerField(blank=True, null=True)),
                ('CodRamo', models.CharField(blank=True, max_length=10, null=True)),
                ('CodCliente', models.CharField(blank=True, max_length=20, null=True)),
                ('Prioridad', models.PositiveIntegerField(blank=True, null=True)),
                ('TipoCosto', models.CharField(blank=True, max_length=5, null=True)),
                ('Fiscal', models.PositiveIntegerField(blank=True, null=True)),
                ('DescProyecto', models.TextField(blank=True, null=True)),
                ('FechaRec', models.DateTimeField(blank=True, null=True)),
                ('FechaIni', models.DateTimeField(blank=True, null=True)),
                ('FechaEIES', models.DateTimeField(blank=True, null=True)),
                ('FechaEst', models.DateTimeField(blank=True, null=True)),
                ('FechaReal', models.DateTimeField(blank=True, null=True)),
                ('IPCoordinador', models.CharField(blank=True, max_length=50, null=True)),
                ('Abierto', models.IntegerField(blank=True, null=True)),
                ('HorasTotales', models.FloatField(blank=True, default=0.0, help_text='Suma total de horas (Regular, Extra, Comp) registradas para este proyecto.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tblTransacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateTimeField()),
                ('IP', models.CharField(max_length=15)),
                ('HoraRegular', models.FloatField(blank=True, null=True)),
                ('HoraExtra', models.FloatField(blank=True, null=True)),
                ('HoraComp', models.FloatField(blank=True, null=True)),
                ('CodRamo', models.CharField(blank=True, max_length=10, null=True)),
                ('CodProyecto', models.ForeignKey(db_column='CodProyecto', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='SIA.tblproyectos')),
            ],
            options={
                'verbose_name_plural': 'tblTransacciones',
                'unique_together': {('Fecha', 'IP', 'CodProyecto')},
            },
        ),
    ]
