# Generated by Django 5.0.14 on 2025-07-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodProyecto', models.CharField(max_length=25)),
                ('NomProyecto', models.TextField()),
                ('CodCuenta', models.PositiveIntegerField()),
                ('CodRamo', models.CharField(max_length=10)),
                ('CodCliente', models.CharField(max_length=20)),
                ('Prioridad', models.PositiveIntegerField()),
                ('TipoCosto', models.CharField(max_length=5)),
                ('Fiscal', models.PositiveIntegerField()),
                ('DescProyecto', models.TextField()),
                ('FechaRec', models.DateTimeField()),
                ('FechaIni', models.DateTimeField()),
                ('FechaEIES', models.DateTimeField()),
                ('FechaEst', models.DateTimeField()),
                ('FechaReal', models.DateTimeField()),
                ('IPCoordinador', models.CharField(max_length=50)),
                ('Abierto', models.IntegerField()),
            ],
        ),
    ]
