# Generated by Django 5.0.14 on 2025-07-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIA_Proyecto_CC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIA.sia')),
            ],
        ),
    ]
