# Generated by Django 5.0.14 on 2025-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblproyectos',
            name='horas_especificador',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='tblproyectos',
            name='horas_estimador',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
