# Generated by Django 5.0.14 on 2025-07-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0002_sia_proyecto_cc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sia',
            name='Abierto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='CodCliente',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='CodCuenta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='CodRamo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='DescProyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='FechaEIES',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='FechaEst',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='FechaIni',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='FechaReal',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='FechaRec',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='Fiscal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='IPCoordinador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='NomProyecto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='Prioridad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sia',
            name='TipoCosto',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
