# Generated by Django 5.0.14 on 2025-07-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0003_alter_sia_abierto_alter_sia_codcliente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SIA_Proyecto_CC',
        ),
    ]
