# Generated by Django 5.0.14 on 2025-07-31 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIA', '0004_delete_sia_proyecto_cc'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SIA',
            new_name='tblProyectos',
        ),
    ]
