# Generated by Django 5.0.14 on 2025-06-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nombre_oficial', models.TextField()),
                ('descripcion_orden_compra', models.TextField()),
                ('tipo_licitacion', models.CharField(max_length=20)),
                ('num_propuesta_ganadora', models.CharField(max_length=50)),
                ('nombre_vendor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALLY CLOSED', 'Finally Closed'), ('CLOSED', 'Cosed')], db_default='OPEN', max_length=25)),
                ('creation_date', models.DateField()),
                ('closed_date', models.DateField()),
                ('fecha_adjudicacion', models.DateField()),
                ('fiscal_year', models.PositiveIntegerField()),
                ('fiscal_month', models.PositiveIntegerField()),
                ('original_amount', models.FloatField()),
                ('actual_amount', models.FloatField()),
                ('billed_amount', models.FloatField()),
                ('max_due_date', models.DateField()),
                ('max_promised_date', models.DateField()),
            ],
        ),
    ]
