# Generated by Django 5.0.14 on 2025-08-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('rubro', models.CharField(blank=True, max_length=15, null=True)),
                ('tipo_licitacion', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_licitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_propuesta_ganadora', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FINALLY CLOSED', 'Finally Closed'), ('CLOSED', 'Cosed')], db_default='OPEN', max_length=25)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_adjudicacion', models.DateTimeField(blank=True, null=True)),
                ('fiscal_year', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_month', models.PositiveIntegerField(blank=True, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('monto_contrato_original', models.FloatField(blank=True, null=True)),
                ('monto_pagado', models.FloatField(blank=True, null=True)),
                ('fecha_promesa', models.DateTimeField(blank=True, null=True)),
                ('fecha_maxima_entrega', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCC_Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
