# Generated by Django 5.0.14 on 2025-08-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0001_initial'),
        ('licitaciones', '0002_alter_licitacion_estado_lic'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='licitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos', to='licitaciones.licitacion', verbose_name='Licitacion'),
        ),
    ]
