# Generated by Django 5.0.14 on 2025-07-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0002_proyectocc_contrato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='num_propuesta_ganadora',
            new_name='numero_contrato',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='actual_amount',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='billed_amount',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='closed_date',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='descripcion_orden_compra',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='max_due_date',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='max_promised_date',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_oficial',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='nombre_vendor',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='original_amount',
        ),
        migrations.AddField(
            model_name='contrato',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_maxima_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fecha_promesa',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_contrato_original',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='monto_pagado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_licitacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='numero_propuesta_ganadora',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='rubro',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_adjudicacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiscal_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_licitacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
