# Generated by Django on [fecha actual]

from django.db import migrations

def populate_licitacion_fk(apps, schema_editor):
    """
    Migración de datos: vincula los contratos existentes con sus licitaciones
    basándose en el campo numero_licitacion
    """
    # Obtener los modelos para esta migración
    Contrato = apps.get_model('contratos', 'Contrato')
    Licitacion = apps.get_model('licitaciones', 'Licitacion')
    
    # Contadores para estadísticas
    vinculados = 0
    no_encontrados = 0
    sin_numero = 0
    errores = []
    
    print("Iniciando migración de datos para vincular contratos con licitaciones...")
    
    # Iterar sobre todos los contratos existentes
    for contrato in Contrato.objects.all():
        if contrato.numero_licitacion:
            # Si el contrato tiene número de licitación, buscar la licitación correspondiente
            try:
                licitacion = Licitacion.objects.get(rfq=contrato.numero_licitacion)
                contrato.licitacion = licitacion
                contrato.save()
                vinculados += 1
                print(f"✓ Contrato {contrato.numero_contrato} vinculado con licitación {licitacion.rfq}")
                
            except Licitacion.DoesNotExist:
                error_msg = f"⚠️  Contrato {contrato.numero_contrato}: No se encontró licitación con RFQ '{contrato.numero_licitacion}'"
                print(error_msg)
                errores.append(error_msg)
                no_encontrados += 1
                
            except Licitacion.MultipleObjectsReturned:
                error_msg = f"❌ Contrato {contrato.numero_contrato}: Múltiples licitaciones encontradas para RFQ '{contrato.numero_licitacion}'"
                print(error_msg)
                errores.append(error_msg)
                no_encontrados += 1
                
            except Exception as e:
                error_msg = f"❌ Error inesperado en contrato {contrato.numero_contrato}: {str(e)}"
                print(error_msg)
                errores.append(error_msg)
                no_encontrados += 1
        else:
            sin_numero += 1
            print(f"ℹ️  Contrato {contrato.numero_contrato}: Sin número de licitación")
    
    # Mostrar estadísticas finales
    print("\n" + "="*60)
    print("RESUMEN DE MIGRACIÓN:")
    print("="*60)
    print(f"📊 Contratos procesados: {Contrato.objects.count()}")
    print(f"✅ Contratos vinculados exitosamente: {vinculados}")
    print(f"⚠️  Contratos sin licitación encontrada: {no_encontrados}")
    print(f"ℹ️  Contratos sin número de licitación: {sin_numero}")
    
    if errores:
        print(f"\n❌ ERRORES ENCONTRADOS ({len(errores)}):")
        for error in errores:
            print(f"   {error}")
    
    print("="*60)
    
    # Si hay muchos errores, dar una advertencia
    if no_encontrados > vinculados:
        print("⚠️  ADVERTENCIA: Más contratos sin vincular que vinculados.")
        print("   Revisa los números de licitación en tu base de datos.")

def reverse_populate_licitacion_fk(apps, schema_editor):
    """
    Función reversa: elimina todas las referencias de ForeignKey
    (útil si necesitas revertir la migración)
    """
    Contrato = apps.get_model('contratos', 'Contrato')
    
    print("Revirtiendo migración: eliminando vínculos con licitaciones...")
    count = Contrato.objects.exclude(licitacion__isnull=True).count()
    Contrato.objects.all().update(licitacion=None)
    print(f"✓ Se eliminaron {count} vínculos con licitaciones")

class Migration(migrations.Migration):
    
    dependencies = [
        ('contratos', '0002_contrato_licitacion'),  # Ajusta este número según tu migración anterior
        ('licitaciones', '0002_alter_licitacion_estado_lic'),  # Ajusta según la última migración de licitaciones
    ]

    operations = [
        migrations.RunPython(
            populate_licitacion_fk,
            reverse_populate_licitacion_fk,
            atomic=True,  # Ejecuta toda la migración en una transacción
        ),
    ]