# Generated by Django 5.0.14 on 2025-07-02 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratos', '0003_rename_num_propuesta_ganadora_contrato_numero_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_adjudicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_maxima_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_promesa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
